backend:
  name: github
  repo: dantecalderon/store  

media_folder: content/uploads
public_folder: static/uploads

collections:
  - name: men
    label: Hombres
    folder: content/products
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: title, label: "Nombre del producto" }
      # - { name: path, label: Path, default: "{{slug}}" }
      - { name: price, label: "Precio", widget: number, valueType: float, min: 0, max: 9999, default: "0.0", required: true }
      - { label: Categorias (Separar con comas), name: categories, widget: list }
      - { label: Colores (Separar con comas), name: colors, widget: list }
      - { label: Tama침os (Separar con comas), name: sizes, widget: list }
      - { label: "Imagen Principal", name: thumbnail, widget: image }
      - { name: description, label: "Descripci칩n del producto", widget: markdown }

  - name: women
    label: Mujeres
    folder: content/products
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: title, label: "Nombre del producto" }
      # - { name: path, label: Path, default: "{{slug}}" }
      - { name: price, label: "Precio", widget: number, valueType: float, min: 0, max: 9999, default: "0.0", required: true }
      - { label: Categorias (Separar con comas), name: categories, widget: list }
      - { label: Colores (Separar con comas), name: colors, widget: list }
      - { label: Tama침os (Separar con comas), name: sizes, widget: list }
      - { label: "Imagen Principal", name: thumbnail, widget: image }
      - { name: description, label: "Descripci칩n del producto", widget: markdown }