backend:
  name: github
  repo: dantecalderon/store  

media_folder: content/uploads
public_folder: static/uploads

collections:
  - name: shirts
    label: Camisas
    folder: content/products
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: title, label: "Nombre del producto" }
      # - { name: path, label: Path, default: "{{slug}}" }
      - { name: price, label: "Precio", widget: number, valueType: float, min: 0, max: 9999, default: "0.0", required: true }
      - { label: Categorias (Separar con comas), name: categories, widget: list }
      - { label: Color, name: color}
      - { label: Patron, name: pattern}
      - { label: Tamaños Disponibles (Separar con comas), name: sizes, widget: list }
      - { label: "Imagen Principal", name: thumbnail, widget: image }
      - { name: description, label: "Descripción del producto", widget: markdown }

  - name: pants
    label: Pantalones
    folder: content/products
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: title, label: "Nombre del producto" }
      # - { name: path, label: Path, default: "{{slug}}" }
      - { name: price, label: "Precio", widget: number, valueType: float, min: 0, max: 9999, default: "0.0", required: true }
      - { label: Categorias (Separar con comas), name: categories, widget: list }
      - { label: Color, name: color }
      - { label: Tamaños Disponibles (Separar con comas), name: sizes, widget: list }
      - { label: "Imagen Principal", name: thumbnail, widget: image }
      - { name: description, label: "Descripción del producto", widget: markdown }

  - name: suits
    label: Trajes Completos
    folder: content/products
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: title, label: "Nombre del producto" }
      - { name: path, label: Path, default: "{{slug}}" }
      - { name: price, label: "Precio", widget: number, valueType: float, min: 0, max: 9999, default: "0.0", required: true }
      - { label: Categorias (Separar con comas), name: categories, widget: list }
      - { label: Color, name: color }
      - { label: Tamaños Disponibles (Separar con comas), name: sizes, widget: list }
      - { label: "Imagen Principal", name: thumbnail, widget: image }
      - { name: description, label: "Descripción del producto", widget: markdown }

  - name: jaquet
    label: Sacos
    folder: content/products
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: title, label: "Nombre del producto" }
      - { name: path, label: Path, default: "{{slug}}" }
      - { name: price, label: "Precio", widget: number, valueType: float, min: 0, max: 9999, default: "0.0", required: true }
      - { label: Categorias (Separar con comas), name: categories, widget: list }
      - { label: Color, name: color }
      - { label: Tamaños Disponibles (Separar con comas), name: sizes, widget: list }
      - { label: "Imagen Principal", name: thumbnail, widget: image }
      - { name: description, label: "Descripción del producto", widget: markdown }

  - name: corbatas
    label: Corbatas
    folder: content/products
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: title, label: "Nombre del producto" }
      - { name: path, label: Path, default: "{{slug}}" }
      - { name: price, label: "Precio", widget: number, valueType: float, min: 0, max: 9999, default: "0.0", required: true }
      - { label: Categorias (Separar con comas), name: categories, widget: list }
      - { label: Color, name: color }
      - { label: Tamaños Disponibles (Separar con comas), name: sizes, widget: list }
      - { label: "Imagen Principal", name: thumbnail, widget: image }
      - { name: description, label: "Descripción del producto", widget: markdown }