backend:
  name: github
  repo: dantecalderon/store

media_folder: src/assets
public_folder: static/uploads

collections:
  - name: blog
    label: Blog
    folder: _products
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: title, label: "Nombre del producto:" }
      - { name: path, label: Path, default: "{{slug}}" }
      - { name: description, label: "Descripción del producto:", widget: markdown }